### ISSUE TITLE
feature request: include "apt autoremove" in multi-updater

### ISSUE THREAD

**Issue by BernhardOnline** [tasket/Qubes-scripts#4]
Relatively often, an update suggests to remove unused parts via "apt autoremove". it would be extremely handy if the tool did handle that, for example via an option like    --allow-auto-remove    or similar.

Best,

**Comment by tasket** [comment]
@eric-blabla This should handle it... use `--autoremove` option.

Commit: https://github.com/tasket/Qubes-scripts/commit/3d3900aefe57ff02ed8949844557e5931dd48f4b
